### ISSUE TITLE
Occasional ticking entity crash on pure RoN dedicated server, forge version 43.4.4

### ISSUE THREAD

**Issue by TerwalEast** [SoLegendary/ageofcraft#104]
Report is here:

Time: 2024-10-31 13:35:26
Description: Ticking entity

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:557) ~[?:?] {}
	at com.solegendary.reignofnether.unit.goals.RangedAttackBuildingGoal.setNextBlockTarget(RangedAttackBuildingGoal.java:42) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:classloading}
	at com.solegendary.reignofnether.unit.goals.RangedAttackBuildingGoal.setBuildingTarget(RangedAttackBuildingGoal.java:62) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:classloading}
	at com.solegendary.reignofnether.unit.interfaces.AttackerUnit.setAttackBuildingTarget(AttackerUnit.java:54) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:mixin,re:classloading}
	at com.solegendary.reignofnether.unit.interfaces.AttackerUnit.attackClosestEnemy(AttackerUnit.java:187) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:mixin,re:classloading}
	at com.solegendary.reignofnether.unit.interfaces.AttackerUnit.tick(AttackerUnit.java:154) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:mixin,re:classloading}
	at com.solegendary.reignofnether.unit.units.villagers.PillagerUnit.m_8119_(PillagerUnit.java:196) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:mixin,re:classloading}
	at net.minecraft.world.entity.Entity.m_6083_(Entity.java:1730) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:reignofnether.mixins.json:EntityMixin,pl:mixin:APP:reignofnether.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6083_(LivingEntity.java:2732) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerLevel.m_8662_(ServerLevel.java:678) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:662) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:1583) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Reign of Nether (reignofnether), Version: 1.0.6a
		at TRANSFORMER/reignofnether@1.0.6a/com.solegendary.reignofnether.unit.goals.RangedAttackBuildingGoal.setNextBlockTarget(RangedAttackBuildingGoal.java:42)
Stacktrace:
	at java.util.Random.nextInt(Random.java:557) ~[?:?] {}
	at com.solegendary.reignofnether.unit.goals.RangedAttackBuildingGoal.setNextBlockTarget(RangedAttackBuildingGoal.java:42) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:classloading}
	at com.solegendary.reignofnether.unit.goals.RangedAttackBuildingGoal.setBuildingTarget(RangedAttackBuildingGoal.java:62) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:classloading}
	at com.solegendary.reignofnether.unit.interfaces.AttackerUnit.setAttackBuildingTarget(AttackerUnit.java:54) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:mixin,re:classloading}
	at com.solegendary.reignofnether.unit.interfaces.AttackerUnit.attackClosestEnemy(AttackerUnit.java:187) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:mixin,re:classloading}
	at com.solegendary.reignofnether.unit.interfaces.AttackerUnit.tick(AttackerUnit.java:154) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:mixin,re:classloading}
	at com.solegendary.reignofnether.unit.units.villagers.PillagerUnit.m_8119_(PillagerUnit.java:196) ~[reignofnether-1.0.6a.jar%2399!/:1.0.6a] {re:mixin,re:classloading}
	at net.minecraft.world.entity.Entity.m_6083_(Entity.java:1730) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:reignofnether.mixins.json:EntityMixin,pl:mixin:APP:reignofnether.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6083_(LivingEntity.java:2732) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerLevel.m_8662_(ServerLevel.java:678) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:662) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: reignofnether:ravager_unit (com.solegendary.reignofnether.unit.units.villagers.RavagerUnit)
	Entity ID: 19115
	Entity Name: entity.reignofnether.ravager_unit
	Entity's Exact location: 16.38, -38.00, -70.38
	Entity's Block location: World: (16,-38,-71), Section: (at 0,10,9 in 1,-3,-5; chunk contains blocks 16,-64,-80 to 31,319,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: [PillagerUnit['entity.reignofnether.pillager_unit'/18623, l='ServerLevel[qwert]', x=16.38, y=-36.35, z=-70.38]]
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:1583) [?:?] {}

-- Affected level --
Details:
	All players: 2 total; [ServerPlayer['TerwalEast'/208, l='ServerLevel[qwert]', x=25.35, y=2.00, z=-98.78], ServerPlayer['114514cucumber'/1970, l='ServerLevel[qwert]', x=-7.58, y=2.00, z=-19.92]]
	Chunk stats: 6784
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-38,0), Section: (at 0,10,0 in 0,-3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 45836 game time, 45836 day time
	Level name: qwert
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23101!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:1583) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1017658952 bytes (970 MiB) / 2785017856 bytes (2656 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i3-12100
	Identifier: Intel64 Family 6 Model 151 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: OrayIddDriver Device
	Graphics card #0 vendor: Shanghai Best Oray Information Technology Co., Ltd.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=17.1.58.818
	Graphics card #1 name: Intel(R) UHD Graphics 730
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x4692
	Graphics card #1 versionInfo: DriverVersion=31.0.101.4953
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 36072.70
	Virtual memory used (MB): 10356.14
	Swap memory total (MB): 3532.20
	Swap memory used (MB): 157.39
	JVM Flags: 1 total; -Xmx8G
	Server Running: true
	Player Count: 2 / 20; [ServerPlayer['TerwalEast'/208, l='ServerLevel[qwert]', x=25.35, y=2.00, z=-98.78], ServerPlayer['114514cucumber'/1970, l='ServerLevel[qwert]', x=-7.58, y=2.00, z=-19.92]]
	Data Packs: vanilla, mod:reignofnether (incompatible), mod:forge, file/datapack_reign_of_nether(2024-10-28 19-46-39 574).zip
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.4.4.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: NOSIGNATURE
		reignofnether-1.0.6a.jar                          |Reign of Nether               |reignofnether                 |1.0.6a              |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.4.4-universal.jar                 |Forge                         |forge                         |43.4.4              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Crash Report UUID: 2c05c494-a798-44b4-95ac-a7e9c20d646a
	FML: 43.4
	Forge: net.minecraftforge:43.4.4

**Comment by zvshka** [comment]
I suggest to use mod Neruina as temporary (or possibly not temporary) fix

**Comment by ColinVaughn** [comment]
this has been fixed they are testing @zvshka

**Comment by SoLegendary** [comment]
fixed in 1.0.11
